name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/restaurant_2.png
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/dishbox_1_x2.svg
  - assets/vectors/star_66_x2.svg
  - assets/vectors/star_65_x2.svg
  - assets/vectors/dishbox_4_x2.svg
  - assets/vectors/star_64_x2.svg
  - assets/vectors/dishbox_7_x2.svg
  - assets/vectors/star_6_x2.svg
  - assets/vectors/dishbox_9_x2.svg
  - assets/vectors/eye_x2.svg
  - assets/vectors/eye_1_x2.svg
  - assets/images/image_2.png
  - assets/images/restaurant_1.png
  - assets/vectors/dishbox_x2.svg
  - assets/vectors/iconclock_outline_x2.svg
  - assets/vectors/iconuser_7_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/iconuser_2_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/iconhome_5_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/logo.svg
  - assets/images/logo-color-cut.png
  - assets/images/las_12.jpeg
  - assets/images/las_11.jpeg
  - assets/images/las_1.jpeg
  - assets/images/image_2.png
  - assets/images/restaurant_1.png
  - assets/vectors/iconleaf_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/iconeuro_1_x2.svg
  - assets/vectors/iconeuro_x2.svg
  - assets/vectors/iconecology_book_x2.svg
  - assets/vectors/star_62_x2.svg
  - assets/images/image_2.png
  - assets/images/restaurant_1.png
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/star_68_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/iconleaf_1_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/food_1_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/dishbox_5_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/images/las_1.jpeg
  - assets/images/las_12.jpeg
  - assets/images/las_11.jpeg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/group_6_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/images/restaurant_2.png
  - assets/vectors/dishbox_8_x2.svg
  - assets/vectors/star_63_x2.svg
  - assets/vectors/star_69_x2.svg
  - assets/vectors/dishbox_6_x2.svg
  - assets/vectors/star_67_x2.svg
  - assets/vectors/dishbox_3_x2.svg
  - assets/vectors/star_61_x2.svg
  - assets/vectors/dishbox_2_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/iconsettings_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/iconfile_text_1_x2.svg
  - assets/vectors/icongift_x2.svg
  - assets/vectors/group_5_x2.svg
  - assets/vectors/group_8_x2.svg
  - assets/images/image_2.png
  - assets/images/ellipse_2.png
  - assets/images/restaurant_5.jpeg
  - assets/images/ellipse_4.png
  - assets/images/restaurant_4.jpeg
  - assets/images/restaurant_2.png
  - assets/images/vector.png
  - assets/images/restaurant_3.png
  - assets/images/ellipse.png
  - assets/images/restaurant_1.png
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/iconhome_1_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/search_icon_x2.svg
  - assets/vectors/iconuser_3_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/images/ellipse_2.png
  - assets/images/vector.png
  - assets/images/ellipse.png
  - assets/images/ellipse_4.png
  - assets/vectors/group_4_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/group_7_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/iconmap_pin_2_x2.svg
  - assets/vectors/group_9_x2.svg
  - assets/vectors/star_1_x2.svg
  - assets/vectors/star_3_x2.svg
  - assets/vectors/star_5_x2.svg
  - assets/vectors/star_2_x2.svg
  - assets/vectors/star_41_x2.svg
  - assets/vectors/search_icon_4_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/star_31_x2.svg
  - assets/vectors/star_11_x2.svg
  - assets/vectors/star_21_x2.svg
  - assets/vectors/star_4_x2.svg
  - assets/vectors/star_51_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/iconmap_pin_x2.svg
  - assets/vectors/grommet_iconsgoogle_x2.svg
  - assets/vectors/search_icon_1_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/iconmap_pin_1_x2.svg
  - assets/images/image_2.png
  - assets/images/reservation_img.jpeg
  - assets/vectors/iconuser_6_x2.svg
  - assets/vectors/iconhome_2_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/search_icon_3_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/images/image_2.png
  - assets/images/h_1.jpeg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/iconuser_x2.svg
  - assets/vectors/search_icon_2_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/iconhome_3_x2.svg
  - assets/images/image_2.png
  - assets/vectors/ellipse_8_x2.svg
  - assets/vectors/iconhome_4_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/iconuser_1_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/ellipse_7_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/images/image_2.png
  - assets/vectors/iconaward_x2.svg
  - assets/vectors/iconhome_x2.svg
  - assets/vectors/iconfile_text_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/iconlog_out_x2.svg
  - assets/vectors/iconhelp_circle_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/iconuser_8_x2.svg
  - assets/vectors/iconuser_9_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/iconsettings_1_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/icongift_1_x2.svg
  - assets/images/restaurant_5.jpeg
  - assets/images/restaurant_1.png
  - assets/images/restaurant_3.png
  - assets/images/image_2.png
  - assets/images/restaurant_2.png
  - assets/images/restaurant_4.jpeg
  - assets/vectors/iconuser_4_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/icontrash_2_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/iconhome_6_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/images/image_2.png
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/vector_14_x2.svg

