// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKeuKGSBD6rgwCirR-AzZ0v8Bo-sU72Ag',
    appId: '1:265295731397:web:0869120b2ea2362c0f2eac',
    messagingSenderId: '265295731397',
    projectId: 'apdc2024groupproject',
    authDomain: 'apdc2024groupproject.firebaseapp.com',
    storageBucket: 'apdc2024groupproject.appspot.com',
    measurementId: 'G-0D9J554F08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAY9TRsz2j8VJqXB5tnO_2GmfGG_3fHxY',
    appId: '1:265295731397:android:e0643dd1333cd6db0f2eac',
    messagingSenderId: '265295731397',
    projectId: 'apdc2024groupproject',
    storageBucket: 'apdc2024groupproject.appspot.com',
  );
}
