// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcO-fgSN8C1ldU3_uI-U2wPmdmOpIBmTk',
    appId: '1:457077558457:web:b3614297746ded39735f68',
    messagingSenderId: '457077558457',
    projectId: 'adc-2324-group-project',
    authDomain: 'adc-2324-group-project.firebaseapp.com',
    storageBucket: 'adc-2324-group-project.appspot.com',
    measurementId: 'G-JMMQVG237R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLd5UBe9OLfoTyz83ljA5G87UU1xyAzc',
    appId: '1:457077558457:android:0872c0e938d66a5f735f68',
    messagingSenderId: '457077558457',
    projectId: 'adc-2324-group-project',
    storageBucket: 'adc-2324-group-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf4vUM-xgrzTRp_R9LFNumVLhsFehZH4A',
    appId: '1:457077558457:ios:c985d9bf31be6cf8735f68',
    messagingSenderId: '457077558457',
    projectId: 'adc-2324-group-project',
    storageBucket: 'adc-2324-group-project.appspot.com',
    iosBundleId: 'com.example.adcHandsonSession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf4vUM-xgrzTRp_R9LFNumVLhsFehZH4A',
    appId: '1:457077558457:ios:c985d9bf31be6cf8735f68',
    messagingSenderId: '457077558457',
    projectId: 'adc-2324-group-project',
    storageBucket: 'adc-2324-group-project.appspot.com',
    iosBundleId: 'com.example.adcHandsonSession',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcO-fgSN8C1ldU3_uI-U2wPmdmOpIBmTk',
    appId: '1:457077558457:web:1901d1d42fe8401f735f68',
    messagingSenderId: '457077558457',
    projectId: 'adc-2324-group-project',
    authDomain: 'adc-2324-group-project.firebaseapp.com',
    storageBucket: 'adc-2324-group-project.appspot.com',
    measurementId: 'G-WD5T2WHJ4G',
  );

}